baseurl = "http://duydo.me/"
copyright = "Copyright © 2016"
disqusshortname = "duydo"
languagecode = "en-US"
paginate = 5
pluralizelisttitles = false
theme = "casper"
title = "Duy Do"

[params]
#logo = "images/logo.jpg"
#cover = "images/ml_pictogram.png"
description = "A Father. A Husband. A Software Engineer."
googleAnalyticsUserID = "UA-68329720-1"
hideHUGOSupport = true
#githubName = "duydo"
#twitterName = "duydo"
author="duydo"

[taxonomies]
tag =  "tags"

[permalinks]
post = "/:slug/"
page = "/:filename/"


[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -300

[[menu.main]]
identifier = "services"
name = "Services"
url = "/services"
weight = -200


[[menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = 101

[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
