baseURL = "http://duydo.me/"
title = "Duy Do"
enableRobotsTXT = true
enableEmoji = true
theme = "jane"

defaultContentLanguage = "en"
hasCJKLanguage = false
paginate = 5
rssLimit = 20
disqusShortname = "duydo"
#googleAnalytics = "UA-68329720-1"
# Google Analytics 4
googleAnalytics = "G-MWQHCX1NZ9"
copyright = "Duy Do"
enableGitInfo = true

mainSections = ["post"]

[author]
name = "duydo"
url = "/about"


[languages.en]
languageCode = "en"


[markup.highlight]
anchorLineNos = true
codeFences = true
guessSyntax = true
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = true
noHl = false
style = 'monokai'
tabWidth = 4


[[menu.main]]
name = "Home"
weight = 5
identifier = "home"
pageref = "/"

[[menu.main]]
name = "Archive"
weight = 10
identifier = "archive"
pageref = "/post/"

[minify]
  minifyOutput = true


[params]
since = "2007"
homeFullContent = false
rssFullContent = true

logoTitle = "Duy Do"
keywords = ["Duy Do", "duydo", "software", "engineering", "computer", "computer science", "python", "java", "elasticsearch", "programming", "programming languges"]
description = "Tầm nhìn ta thật ngắn mà đã thấy bao thứ để làm — Alan Turing"

dateFormatToUse = "Jan 02, 2006"
showAuthorInfo = false
showReadMore = false
moreMeta = true

toc = false
photoswipe = true
customCSS = ['duydo_me.css']
customJS = []
archive-paginate = 100

[params.commentCount.disqus]
enable = false

[params.search.google]
enable = true
title = 'Seach for duydo.me'
id = '006487661450986107425:lgdmnhi9skm'

[params.social]
g-github = "https://github.com/duydo"
c-twitter = "https://twitter.com/duydo"
# e-linkedin = "https://www.linkedin.com/in/duydo/"


[permalinks]
post = "/:slug/"
'/' = "/:filename/"

[sitemap]
changefreq = "weekly"
priority = 0.5
filename = "sitemap.xml"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
