baseURL = "http://duydo.me/"
title = "Duy Do"
enableRobotsTXT = true
enableEmoji = true
theme = "jane"

hasCJKLanguage = false
paginate = 20
rssLimit = 20
disqusShortname = "duydo"
googleAnalytics = "UA-68329720-1"
copyright = "Duy Do"

enableGitInfo = true

# Highlight options.
# See https://gohugo.io/content-management/syntax-highlighting/
PygmentsCodeFences = true
PygmentsUseClasses = true
PygmentsCodefencesGuessSyntax = true
PygmentsOptions = "linenos=table"



[permalinks]
post = "/:slug/"
page = "/:filename/"


defaultContentLanguage = "en"
[languages.en]
  languageCode = "en"

[author]
  name = "duydo"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]
  name = "Home"
  weight = 5
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Archives"
  weight = 10
  identifier = "archives"
  url = "/post/"


 [[menu.main]]
   name = "Consulting"
   weight = 20
   identifier = "consulting"
   url = "/consulting"
   hasChildren = true
  
#
# [[menu.main]]
#   name = "Books"
#   weight = 20
#   identifier = "books"
#   url = "/categories/books"

 [[menu.main]]
   name = "About"
   weight = 100
   identifier = "about"
   url = "/about"
#
# [[menu.main]]
#   name = "Tags"
#   weight = 30
#   identifier = "tags"
#   url = "/tags/"
#
# [[menu.main]]
#  name = "Code"
#  weight = 40
#  identifier = "code"
#  url = "https://github.com/duydo"

[params]
  since = "2007"
  homeFullContent = false
  rssFullContent = true

  logoTitle = "Duy Do"
  keywords = ["Duy Do", "duydo", "software", "engineering", "computer", "computer science", "python", "java", "elasticsearch", "programming", "programming languges"]
  description = "Thoughts on people, parenting, books and technology."

  dateFormatToUse = "Jan 02, 2006"
  showAuthorInfo = true
  moreMeta = true
  showReadMore = true
  toc = true
  photoswipe = true
  customCSS = ['custom.css']
  customJS = []
  archive-paginate = 100

  [params.commentCount.disqus]
    enable = false

  [params.search.google]
      enable = true
      title = 'Seach for duydo.me'
      id = '006487661450986107425:lgdmnhi9skm'

  [params.social]
    g-github = "https://github.com/duydo"
    c-twitter = "https://twitter.com/duydo"
    # e-linkedin = "https://www.linkedin.com/in/duydo/"
