baseURL = "http://duydo.me/"
title = "Duy Do's weblog"
enableRobotsTXT = true
enableEmoji = true
theme = "jane"

hasCJKLanguage = false
paginate = 5
rssLimit = 20
disqusShortname = "duydo"
googleAnalytics = "UA-68329720-1"
copyright = "Duy Do"

# Highlight options.
# See https://gohugo.io/content-management/syntax-highlighting/
PygmentsCodeFences = true
PygmentsUseClasses = true
PygmentsCodefencesGuessSyntax = true
PygmentsOptions = "linenos=table"

[permalinks]
post = "/:slug/"
page = "/:filename/"

# language support # en / zh-cn / other... translations present in i18n/
defaultContentLanguage = "en"           # Default language to use
[languages.en]
  languageCode = "en"

[author]                  # essential                     # 必需
  name = "Duy Do"

[sitemap]                 # essential                     # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]
  name = "Posts"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"

[params]
  since = "2016"            # Site creation time          # 站点建立时间
  homeFullContent = false   # if false, show post summaries on home page. Othewise show full content.
  rssFullContent = true     # if false, Rss feed instead of the summary

  # site info (optional)                                  # 站点信息（可选，不需要的可以直接注释掉）
  logoTitle = "Duy Do"        # default: the title value    # 默认值: 上面设置的title值
  keywords = ["Duy Do", "duydo","software", "engineering", "computer", "computer science"]
  description = "Duy Do's personal website"

  dateFormatToUse = "2006-01-02"
  showAuthorInfo = true
  moreMeta = true
#  toc = true
  photoswipe = true
  customCSS = ['custom.css']
  customJS = []

  [params.social]
    g-github = "https://github.com/duydo"
    c-twitter = "https://twitter.com/duydo"
    e-linkedin = "https://www.linkedin.com/in/duydo/"

