baseURL = "http://duydo.me/"
title = "Duy Do - Thougths on computer"
enableRobotsTXT = true
enableEmoji = true
theme = "jane"

hasCJKLanguage = false
paginate = 5
rssLimit = 20
disqusShortname = "duydo"
googleAnalytics = "UA-68329720-1"
copyright = "Duy Do"

# Highlight options.
# See https://gohugo.io/content-management/syntax-highlighting/
PygmentsCodeFences = true
PygmentsUseClasses = true
PygmentsCodefencesGuessSyntax = true
PygmentsOptions = "linenos=table"

[permalinks]
post = "/:slug/"
page = "/:filename/"

defaultContentLanguage = "en"
[languages.en]
  languageCode = "en"

[author]
  name = "duydo"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

# [[menu.main]]
#   name = "Home"
#   weight = 10
#   identifier = "home"
#   url = "/"
[[menu.main]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
#
# [[menu.main]]
#  name = "Code"
#  weight = 40
#  identifier = "code"
#  url = "https://github.com/duydo"

[params]
  since = "2016"
  homeFullContent = false
  rssFullContent = true

  logoTitle = "Duy Do"
  keywords = ["Duy Do", "duydo", "software", "engineering", "computer", "computer-science", "python", "java", "elasticsearch"]
  description = "Duy Do's personal website"

  dateFormatToUse = "Jan 02, 2006"
  showAuthorInfo = true
  moreMeta = true
  showReadMore = false
  toc = true
  photoswipe = true
  customCSS = ['custom.css']
  customJS = []

  [params.commentCount.disqus]
    enable = false

  [params.social]
    g-github = "https://github.com/duydo"
    c-twitter = "https://twitter.com/duydo"
    # e-linkedin = "https://www.linkedin.com/in/duydo/"
