#!/usr/bin/env bash
function deploy() {
    rm -rf ./public
    hugo
    export GIT_DEPLOY_DIR=public
    export GIT_DEPLOY_BRANCH=master
    export GIT_DEPLOY_USERNAME="Duy Do"
    export GIT_DEPLOY_EMAIL=doquocduy@gmail.com
    echo 'duydo.me' > ./public/CNAME
    ./deploy.sh
}

case "$1" in
    run)
        hugo server --buildDrafts -w
        ;;
    build)
        hugo
        ;;
    deploy)
        deploy
        ;;
    *)
        echo "Usage: ./manage <run|build|deploy>"
        exit 3
esac
exit 0
