#!/usr/bin/env bash

case "$1" in
    run)
        hugo server --buildDrafts -w
        ;;
    build)
        hugo
        ;;
    deploy)
        echo 'duydo.me' > ./public/CNAME
        ./deploy.sh
        ;;
    *)
        echo "Usage: ./manage <run|build|deploy>"
        exit 3
esac
exit 0
