#!/usr/bin/env bash
me=$(basename "$0")


function deploy() {
    rm -rf ./public
    hugo
    cp ./CNAME ./public/CNAME
    export GIT_DEPLOY_DIR=public
    export GIT_DEPLOY_BRANCH=master
    export GIT_DEPLOY_USERNAME="duydo"
    export GIT_DEPLOY_EMAIL=doquocduy@gmail.com
    ./bin/deploy.sh
    rm -rf ./public
}

case "$1" in
    run)
        hugo server --buildDrafts -w
        ;;
    build)
        hugo
        ;;
    sync)
        rm -rf ./public
        git add --all && git commit -am "$2" && git push
        ;;
    deploy)
        deploy
        ;;
    *)
        echo "Usage: $me <run|build|sync|deploy>"
        exit 3
esac
exit 0
